DROP TABLE IF EXISTS build;
DROP TYPE IF EXISTS build_cause;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS repo;
DROP TABLE IF EXISTS login_history;
DROP TABLE IF EXISTS account;
DROP TYPE IF EXISTS account_type;
DROP TABLE IF EXISTS raw_file;
