[package]
name = "backend"
version = "3.0.0"
authors = ["Poggit <poggitbot@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
config = {path = "../config"}
futures = "0.3.5"
serde_json = "1.0.53"
tokio = {version = "0.2.21", features = ["full"]}
